DROP TABLE IF EXISTS chronicle;
CREATE TABLE chronicle (id INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1) CONSTRAINT chronicle_pk PRIMARY KEY, parentId INT DEFAULT null, tag VARCHAR(50) DEFAULT NULL, description VARCHAR(400) DEFAULT NULL, inserted TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (parentId) 
    REFERENCES chronicle(id));